Story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls'))
]  

tugas/urls.py
from django.urls import path
from . import views
from .views import status


app_name = 'tugas'

urlpatterns = [
    path('',views.status,name='status'),
    


]

tugas/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    status = models.TextField('status', max_length = 100)

    def __str__(self):
        return self.status

tugas/forms.py
from django import forms
from .models import Status
##Create your forms here
class StatusForm(forms.ModelForm):
    status = forms.CharField(widget=forms.TextInput, required=True)
    class Meta:
        model = Status
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

tugas/views.py
from .models import Status
from .forms import StatusForm
from django.shortcuts import render,redirect
from . import forms

# Create your views here.

def status(request):
	stats = Status.objects.all()
	if (request.method == 'POST'):
		form = forms.StatusForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect('/')
	else:
		form = forms.StatusForm()
	return render(request, 'pages/index.html', {'stats': stats, 'form':form})

tugas/templates/pages/index.html
{% load static %}
{% block content %}
<!DOCTYPE html>


<html lang="en" dir="ltr">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700,800&display=swap" rel="stylesheet">
</head>
 

<div class="container ml-5 mt-5 mr-5">
<h1>Hello, how are you?</h1>
<form action="{% url 'tugas:status' %}" method="post">

    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
</div>

<h1 class = "text-center mt-5 mb-5" style="font-weight:700">Status</h1>
<div class=" col-lg-12 col-md-12 col-sm-12">
<div class="row">
<table class="table">
  <thead style="font-size: 25px">
    <tr>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody style="font-size: 20px">
    {% for stats in stats %}
    <tr>
      <td>{{ stats.status }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
</div>
</div>
{% endblock %}